[package]
name = "day11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { git = "https://github.com/irevoire/aoc" }
parse-display = "0.6.0"

[dev-dependencies]
insta = "1.23.0"
